import { BaseLayout, CurrentUser } from "@/lib/base";
import { Effect } from "effect";
import type { Metadata } from "next";
import { cachedFunction3 } from "./cached";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default BaseLayout.build(({ children }) =>
  Effect.gen(function* () {
    const user = yield* CurrentUser;
    const value = yield* cachedFunction3();

    return (
      <html>
        <body>
          <div>
            Layout {user.name} <br />
            {value.name}
            <br />
            {children}
          </div>
        </body>
      </html>
    );
  })
);
